### ISSUE TITLE
Mobile links not working

### ISSUE THREAD

**Issue by cubicbyte** [HirbodBehnam/RedditDownloaderBot#25]
Hi! Links copied from mobile app stopped working, throwing this error:

Corrupted link. Paste the link in your browser and send the redirected link to bot.

Link example: https://www.reddit.com/r/lotrmemes/s/vJ9bjozmI2

**Comment by HirbodBehnam** [comment]
Hi
Thanks a lot for bringing this to my eyes!
This issue seems to be rooted in the fact that Reddit blocks unauthorized traffic from some data centers (in this case, Hetzner). Before that, I used to use ethernetservers to host my bot, but yesterday I migrated to Hetzner and this is where the issue came from. Based on my old comments, Reddit used to don't care about oauth in redirect links however now it seems that the issue is fixed and Reddit checks the oauth token if provided.
I'll update the server codebase in few minutes. Please check if this is fixed and don't hesitate to open another issue!
